# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.1
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ourdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

  storage:
    # ref. https://min.io/docs/minio/container/index.html
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: miniorootuser
      MINIO_ROOT_PASSWORD: miniorootpass
    volumes:
      - ~/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
