spring:
  application:
    name: toshiten
  datasource:
    url: "jdbc:mysql://localhost:3307/ourdb"
    username: "user1"
    password: "password1"
  mvc:
    hiddenmethod.filter.enabled: true
  cloud:
    aws:
      credentials:
        access-key: "miniorootuser"
        secret-key: "miniorootpass"
      s3:
        endpoint: "http://127.0.0.1:9000"
server:
  port: 8089
logging:
  level:
    com.example.toshiten.repository: DEBUG
    org.springframework.security: WARN
