spring:
  application:
    name: toshiten
  datasource:
    url: "jdbc:mysql://localhost:3307/ourdb"
    username: "user1"
    password: "password1"
  mvc:
    hiddenmethod.filter.enabled: true
server:
  port: 8089
logging:
  level:
    com.example.toshiten.repository: DEBUG
    org.springframework.security: WARN
