INSERT INTO shops (name)
VALUES ('Super Cafe')
     , ('Awesome School')
     , ('Beautiful Restaurant')
     , ('Good Office')
     , ('Miracle Park')
     , ('Diamond Hotel')
     , ('Fantastic Gym')
     , ('Great Hospital')